spring:
  config:
    import: configserver:http://localhost:8888/
  application:
    name: carts-service
  profiles:
    active: development
management:
  endpoints:
    web:
      exposure:
        include: refresh