server:
  port: ${SERVER_PORT}

eureka:
  client:
    enabled: true
    service-url:
      defaultZone: ${EUREKA_URL}
  instance:
    hostname: localhost

spring:
  application:
    name: carts-service
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.MySQL8Dialect
  datasource:
    url: ${DB_URL}?serverTimezone=UTC
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}